backend:
  name: github
  repo: noobee-toolkit/noobee-cms
  branch: main
  base_url: https://noobee-oauth.jacqueslavalmalecaut.workers.dev
  auth_endpoint: /auth
  app_id: Ov23liDLsKIPxSGX6opT
  auth_type: pkce

site_url: https://noobee-cms.pages.dev
media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
